menu:
  主页: /
  归档: /archives
  关于: /about

rss: /atom.xml

archive_date_format: MMM DD
fancybox: true
widgets: #配置页脚显示哪些小挂件
  - category
  - tag
  - tagcloud
  - recent_posts
  - blogroll
duoshuo_shortname: yaochiqkl

#google_analytics:
baidu_tongji: true
favicon: /favicon.png
